apiVersion: v1
kind: Secret
metadata:
  name: de-back-secrets
  namespace: de
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb://admin:de-mongodb-pass@mongodb:27017/appdb?authSource=admin"
  JWT_SECRET: "de-jwt-secret"
  MONGODB_URI: "mongodb://admin:de-mongodb-pass@mongodb:27017/appdb?authSource=admin"
