apiVersion: v1
kind: Service
metadata:
  name: de-back
  namespace: de
  labels:
    app: de-back
    app.kubernetes.io/part-of: de
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: de-back
    app.kubernetes.io/part-of: de
    app.kubernetes.io/component: back
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
