apiVersion: v1
kind: Service
metadata:
  name: ss-todos-api
  namespace: ss
  labels:
    app: ss-todos-api
    app.kubernetes.io/part-of: ss
    app.kubernetes.io/component: todos-api
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: ss-todos-api
    app.kubernetes.io/part-of: ss
    app.kubernetes.io/component: todos-api
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
