apiVersion: v1
kind: Service
metadata:
  name: manual-front
  namespace: manual
  labels:
    app: manual-front
    app.kubernetes.io/part-of: manual
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: manual-front
    app.kubernetes.io/part-of: manual
    app.kubernetes.io/component: front
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
