apiVersion: v1
kind: Secret
metadata:
  name: mono-back-secrets
  namespace: mono
type: Opaque
stringData:
  JWT_SECRET: "mono-jwt-secret"
  SPRING_DATA_MONGODB_URI: "mongodb://admin:mono-mongodb-pass@mongodb:27017/appdb?authSource=admin"
  MONGODB_URI: "mongodb://admin:mono-mongodb-pass@mongodb:27017/appdb?authSource=admin"
