apiVersion: v1
kind: Service
metadata:
  name: front-back
  namespace: front
  labels:
    app: front-back
    app.kubernetes.io/part-of: front
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: front-back
    app.kubernetes.io/part-of: front
    app.kubernetes.io/component: back
  ports:
    - name: http
      port: 8080
      targetPort: 8081
      protocol: TCP
