apiVersion: v1
kind: Service
metadata:
  name: newmono-front
  namespace: newmono
  labels:
    app: newmono-front
    app.kubernetes.io/part-of: newmono
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: newmono-front
    app.kubernetes.io/part-of: newmono
    app.kubernetes.io/component: front
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
