apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-back
  namespace: multi
  labels:
    app: multi-back
    app.kubernetes.io/part-of: multi
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-back
      app.kubernetes.io/part-of: multi
      app.kubernetes.io/component: back
  template:
    metadata:
      labels:
        app: multi-back
        app.kubernetes.io/part-of: multi
        app.kubernetes.io/component: back
    spec:
      containers:
        - name: back
          image: docker.io/firasmah/multi-app-back:run-1774877375494-back
          ports:
            - containerPort: 8085
              protocol: TCP
          envFrom:
            - secretRef:
                name: multi-back-secrets
                optional: true
            - configMapRef:
                name: multi-back-config
                optional: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
