apiVersion: v1
kind: Service
metadata:
  name: multi-back
  namespace: multi
  labels:
    app: multi-back
    app.kubernetes.io/part-of: multi
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: multi-back
    app.kubernetes.io/part-of: multi
    app.kubernetes.io/component: back
  ports:
    - name: http
      port: 8080
      targetPort: 8085
      protocol: TCP
