apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-front
  namespace: post
  labels:
    app: post-front
    app.kubernetes.io/part-of: post
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-front
      app.kubernetes.io/part-of: post
      app.kubernetes.io/component: front
  template:
    metadata:
      labels:
        app: post-front
        app.kubernetes.io/part-of: post
        app.kubernetes.io/component: front
    spec:
      containers:
        - name: front
          image: docker.io/firasmah/post-front:run-1776268691548-front
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: post-front-secrets
                optional: true
            - configMapRef:
                name: post-front-config
                optional: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
