apiVersion: v1
kind: Service
metadata:
  name: post-front
  namespace: post
  labels:
    app: post-front
    app.kubernetes.io/part-of: post
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: post-front
    app.kubernetes.io/part-of: post
    app.kubernetes.io/component: front
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
