apiVersion: v1
kind: Service
metadata:
  name: trial-scan-temp
  namespace: trial
  labels:
    app: trial-scan-temp
    app.kubernetes.io/part-of: trial
    app.kubernetes.io/component: scan-temp
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: trial-scan-temp
    app.kubernetes.io/part-of: trial
    app.kubernetes.io/component: scan-temp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
