apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: df
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "df-mongodb-pass"
  MONGO_DB_NAME: "appdb"
