apiVersion: v1
kind: Service
metadata:
  name: rt-log-message-processor
  namespace: rt
  labels:
    app: rt-log-message-processor
    app.kubernetes.io/part-of: rt
    app.kubernetes.io/component: log-message-processor
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: rt-log-message-processor
    app.kubernetes.io/part-of: rt
    app.kubernetes.io/component: log-message-processor
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
