apiVersion: v1
kind: Secret
metadata:
  name: dfdfdfdf-front-secrets
  namespace: dfdfdfdf
type: Opaque
stringData:
  JWT_SECRET: "dfdfdfdf-jwt-secret"
  SPRING_DATA_MONGODB_URI: "mongodb://admin:dfdfdfdf-mongodb-pass@mongodb:27017/appdb?authSource=admin"
  MONGODB_URI: "mongodb://admin:dfdfdfdf-mongodb-pass@mongodb:27017/appdb?authSource=admin"
