apiVersion: v1
kind: Service
metadata:
  name: fg-front
  namespace: fg
  labels:
    app: fg-front
    app.kubernetes.io/part-of: fg
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: fg-front
    app.kubernetes.io/part-of: fg
    app.kubernetes.io/component: front
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
