apiVersion: v1
kind: Service
metadata:
  name: first-back
  namespace: first
  labels:
    app: first-back
    app.kubernetes.io/part-of: first
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: first-back
    app.kubernetes.io/part-of: first
    app.kubernetes.io/component: back
  ports:
    - name: http
      port: 8080
      targetPort: 8081
      protocol: TCP
