apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-queue-pvc
  namespace: rt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-queue
  namespace: rt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-queue
  template:
    metadata:
      labels:
        app: redis-queue
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-queue-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-queue
  namespace: rt
spec:
  selector:
    app: redis-queue
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
