apiVersion: v1
kind: Service
metadata:
  name: newmono-back
  namespace: newmono
  labels:
    app: newmono-back
    app.kubernetes.io/part-of: newmono
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: newmono-back
    app.kubernetes.io/part-of: newmono
    app.kubernetes.io/component: back
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
