apiVersion: v1
kind: Service
metadata:
  name: ww-back
  namespace: ww
  labels:
    app: ww-back
    app.kubernetes.io/part-of: ww
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: ww-back
    app.kubernetes.io/part-of: ww
    app.kubernetes.io/component: back
  ports:
    - name: http
      port: 8080
      targetPort: 8081
      protocol: TCP
