apiVersion: v1
kind: Service
metadata:
  name: first-front
  namespace: first
  labels:
    app: first-front
    app.kubernetes.io/part-of: first
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: first-front
    app.kubernetes.io/part-of: first
    app.kubernetes.io/component: front
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
