apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbb-frontend
  namespace: bbb
  labels:
    app: bbb-frontend
    app.kubernetes.io/part-of: bbb
    app.kubernetes.io/component: frontend
    managed-by: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbb-frontend
      app.kubernetes.io/part-of: bbb
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app: bbb-frontend
        app.kubernetes.io/part-of: bbb
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/firasmah/bbb-frontend:run-1776789424996-frontend
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: bbb-frontend-secrets
                optional: true
            - configMapRef:
                name: bbb-frontend-config
                optional: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
