apiVersion: apps/v1
kind: Deployment
metadata:
  name: manual-back
  namespace: manual
  labels:
    app: manual-back
    app.kubernetes.io/part-of: manual
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manual-back
      app.kubernetes.io/part-of: manual
      app.kubernetes.io/component: back
  template:
    metadata:
      labels:
        app: manual-back
        app.kubernetes.io/part-of: manual
        app.kubernetes.io/component: back
    spec:
      containers:
        - name: back
          image: docker.io/firasmah/manual-back:run-1776367365825-back
          ports:
            - containerPort: 8081
              protocol: TCP
          envFrom:
            - secretRef:
                name: manual-back-secrets
                optional: true
            - configMapRef:
                name: manual-back-config
                optional: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
