apiVersion: v1
kind: Service
metadata:
  name: mono-github-front
  namespace: mono-github
  labels:
    app: mono-github-front
    app.kubernetes.io/part-of: mono-github
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: mono-github-front
    app.kubernetes.io/part-of: mono-github
    app.kubernetes.io/component: front
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
