apiVersion: v1
kind: Service
metadata:
  name: jojo-front
  namespace: jojo
  labels:
    app: jojo-front
    app.kubernetes.io/part-of: jojo
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: jojo-front
    app.kubernetes.io/part-of: jojo
    app.kubernetes.io/component: front
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
