apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: shopping
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "shopping-mysql-pass"
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "shopping-mysql-pass"
  MYSQL_DATABASE: "appdb"
