apiVersion: v1
kind: Secret
metadata:
  name: df-back-secrets
  namespace: df
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb://admin:df-mongodb-pass@mongodb:27017/appdb?authSource=admin"
  JWT_SECRET: "df-jwt-secret"
  MONGODB_URI: "mongodb://admin:df-mongodb-pass@mongodb:27017/appdb?authSource=admin"
