apiVersion: apps/v1
kind: Deployment
metadata:
  name: df-back
  namespace: df
  labels:
    app: df-back
    app.kubernetes.io/part-of: df
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: df-back
      app.kubernetes.io/part-of: df
      app.kubernetes.io/component: back
  template:
    metadata:
      labels:
        app: df-back
        app.kubernetes.io/part-of: df
        app.kubernetes.io/component: back
    spec:
      containers:
        - name: back
          image: docker.io/firasmah/df-back:run-1777526163726-back
          ports:
            - containerPort: 8081
              protocol: TCP
          envFrom:
            - secretRef:
                name: df-back-secrets
                optional: true
            - configMapRef:
                name: df-back-config
                optional: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
