apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-app-auth-api
  namespace: microservice-app
  labels:
    app: microservice-app-auth-api
    app.kubernetes.io/part-of: microservice-app
    app.kubernetes.io/component: auth-api
    managed-by: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-app-auth-api
      app.kubernetes.io/part-of: microservice-app
      app.kubernetes.io/component: auth-api
  template:
    metadata:
      labels:
        app: microservice-app-auth-api
        app.kubernetes.io/part-of: microservice-app
        app.kubernetes.io/component: auth-api
    spec:
      containers:
        - name: auth-api
          image: docker.io/firasmah/microservice-app-auth-api:run-1776464174646-auth-api
          ports:
            - containerPort: 8081
              protocol: TCP
          envFrom:
            - secretRef:
                name: microservice-app-auth-api-secrets
                optional: true
            - configMapRef:
                name: microservice-app-auth-api-config
                optional: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
