apiVersion: v1
kind: Service
metadata:
  name: microservice-app-auth-api
  namespace: microservice-app
  labels:
    app: microservice-app-auth-api
    app.kubernetes.io/part-of: microservice-app
    app.kubernetes.io/component: auth-api
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: microservice-app-auth-api
    app.kubernetes.io/part-of: microservice-app
    app.kubernetes.io/component: auth-api
  ports:
    - name: http
      port: 8080
      targetPort: 8081
      protocol: TCP
