apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-back
  namespace: dd
  labels:
    app: dd-back
    app.kubernetes.io/part-of: dd
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-back
      app.kubernetes.io/part-of: dd
      app.kubernetes.io/component: back
  template:
    metadata:
      labels:
        app: dd-back
        app.kubernetes.io/part-of: dd
        app.kubernetes.io/component: back
    spec:
      containers:
        - name: back
          image: docker.io/firasmah/dd-back:run-1776271289979-back
          ports:
            - containerPort: 8081
              protocol: TCP
          envFrom:
            - secretRef:
                name: dd-back-secrets
                optional: true
            - configMapRef:
                name: dd-back-config
                optional: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
