apiVersion: v1
kind: Service
metadata:
  name: dd-back
  namespace: dd
  labels:
    app: dd-back
    app.kubernetes.io/part-of: dd
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: dd-back
    app.kubernetes.io/part-of: dd
    app.kubernetes.io/component: back
  ports:
    - name: http
      port: 8080
      targetPort: 8081
      protocol: TCP
