apiVersion: v1
kind: ConfigMap
metadata:
  name: aaa-frontend-config
  namespace: aaa
data:
  PORT: "8080"
  AUTH_API_ADDRESS: "http://auth-api:8081"
  TODOS_API_ADDRESS: "http://todos-api:8082"
  ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"
