apiVersion: v1
kind: Secret
metadata:
  name: yuio-front-secrets
  namespace: yuio
type: Opaque
stringData:
  JWT_SECRET: "yuio-jwt-secret"
  SPRING_DATA_MONGODB_URI: "mongodb://admin:yuio-mongodb-pass@mongodb:27017/appdb?authSource=admin"
  MONGODB_URI: "mongodb://admin:yuio-mongodb-pass@mongodb:27017/appdb?authSource=admin"
