apiVersion: v1
kind: Secret
metadata:
  name: shopping-nodejs-shopping-secrets
  namespace: shopping
type: Opaque
stringData:
  JWT_SECRET: "shopping-jwt-secret"
  SPRING_DATASOURCE_PASSWORD: "shopping-mysql-pass"
  SPRING_DATA_MONGODB_URI: "mongodb://admin:shopping-mongodb-pass@mongodb:27017/appdb?authSource=admin"
  MONGODB_URI: "mongodb://admin:shopping-mongodb-pass@mongodb:27017/appdb?authSource=admin"
  DATABASE_URL: "mysql://admin:shopping-mysql-pass@mysql:3306/appdb"
