apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: rrreeee
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rrreeee-mysql-pass"
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "rrreeee-mysql-pass"
  MYSQL_DATABASE: "appdb"
