apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-back
  namespace: ff
  labels:
    app: ff-back
    app.kubernetes.io/part-of: ff
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-back
      app.kubernetes.io/part-of: ff
      app.kubernetes.io/component: back
  template:
    metadata:
      labels:
        app: ff-back
        app.kubernetes.io/part-of: ff
        app.kubernetes.io/component: back
    spec:
      containers:
        - name: back
          image: docker.io/firasmah/ff-back:run-1776272697171-back
          ports:
            - containerPort: 8081
              protocol: TCP
          envFrom:
            - secretRef:
                name: ff-back-secrets
                optional: true
            - configMapRef:
                name: ff-back-config
                optional: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
