apiVersion: v1
kind: Service
metadata:
  name: ff-back
  namespace: ff
  labels:
    app: ff-back
    app.kubernetes.io/part-of: ff
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: ff-back
    app.kubernetes.io/part-of: ff
    app.kubernetes.io/component: back
  ports:
    - name: http
      port: 8080
      targetPort: 8081
      protocol: TCP
