apiVersion: v1
kind: Service
metadata:
  name: aaa-log-message-processor
  namespace: aaa
  labels:
    app: aaa-log-message-processor
    app.kubernetes.io/part-of: aaa
    app.kubernetes.io/component: log-message-processor
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: aaa-log-message-processor
    app.kubernetes.io/part-of: aaa
    app.kubernetes.io/component: log-message-processor
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
