apiVersion: v1
kind: Service
metadata:
  name: connect-front
  namespace: connect
  labels:
    app: connect-front
    app.kubernetes.io/part-of: connect
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: connect-front
    app.kubernetes.io/part-of: connect
    app.kubernetes.io/component: front
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
