apiVersion: v1
kind: Secret
metadata:
  name: front-secrets
  namespace: daas
type: Opaque
stringData:
  JWT_SECRET: "front-jwt-secret"
  SPRING_DATA_MONGODB_URI: "mongodb://admin:back-mongodb-pass@mongodb:27017/appdb?authSource=admin"
  MONGODB_URI: "mongodb://admin:back-mongodb-pass@mongodb:27017/appdb?authSource=admin"
