apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: gggrrr
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "gggrrr-mongodb-pass"
  MONGO_DB_NAME: "appdb"
