apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: daas
  labels:
    app: back
    managed-by: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back
          image: docker.io/firasmah/monotest-back:run-1774450483596-back
          ports:
            - containerPort: 8081
              protocol: TCP
          envFrom:
            - secretRef:
                name: back-secrets
                optional: true
            - configMapRef:
                name: back-config
                optional: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
