apiVersion: v1
kind: Secret
metadata:
  name: monotest-back-secrets
  namespace: monotest
type: Opaque
stringData:
  JWT_SECRET: "monotest-jwt-secret"
  SPRING_DATA_MONGODB_URI: "mongodb://admin:monotest-mongodb-pass@mongodb:27017/appdb?authSource=admin"
  MONGODB_URI: "mongodb://admin:monotest-mongodb-pass@mongodb:27017/appdb?authSource=admin"
