apiVersion: v1
kind: Service
metadata:
  name: dfdfdfdf-back
  namespace: dfdfdfdf
  labels:
    app: dfdfdfdf-back
    app.kubernetes.io/part-of: dfdfdfdf
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: dfdfdfdf-back
    app.kubernetes.io/part-of: dfdfdfdf
    app.kubernetes.io/component: back
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
