apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-app
  namespace: multi
  labels:
    app: multi-app
    app.kubernetes.io/part-of: multi
    app.kubernetes.io/component: app
    managed-by: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-app
      app.kubernetes.io/part-of: multi
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app: multi-app
        app.kubernetes.io/part-of: multi
        app.kubernetes.io/component: app
    spec:
      containers:
        - name: app
          image: docker.io/firasmah/multi-app:run-1774872012271-app
          ports:
            - containerPort: 8085
              protocol: TCP
          envFrom:
            - secretRef:
                name: multi-app-secrets
                optional: true
            - configMapRef:
                name: multi-app-config
                optional: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
