apiVersion: v1
kind: Service
metadata:
  name: multi-app
  namespace: multi
  labels:
    app: multi-app
    app.kubernetes.io/part-of: multi
    app.kubernetes.io/component: app
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: multi-app
    app.kubernetes.io/part-of: multi
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
