apiVersion: apps/v1
kind: Deployment
metadata:
  name: monotest3-back
  namespace: monotest3
  labels:
    app: monotest3-back
    app.kubernetes.io/part-of: monotest3
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monotest3-back
      app.kubernetes.io/part-of: monotest3
      app.kubernetes.io/component: back
  template:
    metadata:
      labels:
        app: monotest3-back
        app.kubernetes.io/part-of: monotest3
        app.kubernetes.io/component: back
    spec:
      containers:
        - name: back
          image: docker.io/firasmah/monotest3-back:run-1774870530599-back
          ports:
            - containerPort: 8081
              protocol: TCP
          envFrom:
            - secretRef:
                name: monotest3-back-secrets
                optional: true
            - configMapRef:
                name: monotest3-back-config
                optional: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
