apiVersion: v1
kind: Service
metadata:
  name: hhh-log-message-processor
  namespace: hhh
  labels:
    app: hhh-log-message-processor
    app.kubernetes.io/part-of: hhh
    app.kubernetes.io/component: log-message-processor
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: hhh-log-message-processor
    app.kubernetes.io/part-of: hhh
    app.kubernetes.io/component: log-message-processor
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
