apiVersion: apps/v1
kind: Deployment
metadata:
  name: mono55-front
  namespace: mono55
  labels:
    app: mono55-front
    app.kubernetes.io/part-of: mono55
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mono55-front
      app.kubernetes.io/part-of: mono55
      app.kubernetes.io/component: front
  template:
    metadata:
      labels:
        app: mono55-front
        app.kubernetes.io/part-of: mono55
        app.kubernetes.io/component: front
    spec:
      containers:
        - name: front
          image: docker.io/firasmah/mono55-front:run-1774880664338-front
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: mono55-front-secrets
                optional: true
            - configMapRef:
                name: mono55-front-config
                optional: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
