apiVersion: v1
kind: Service
metadata:
  name: ww-front
  namespace: ww
  labels:
    app: ww-front
    app.kubernetes.io/part-of: ww
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: ww-front
    app.kubernetes.io/part-of: ww
    app.kubernetes.io/component: front
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
