apiVersion: v1
kind: Service
metadata:
  name: aaa-todos-api
  namespace: aaa
  labels:
    app: aaa-todos-api
    app.kubernetes.io/part-of: aaa
    app.kubernetes.io/component: todos-api
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: aaa-todos-api
    app.kubernetes.io/part-of: aaa
    app.kubernetes.io/component: todos-api
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
