apiVersion: v1
kind: Service
metadata:
  name: mono2-front
  namespace: mono2
  labels:
    app: mono2-front
    app.kubernetes.io/part-of: mono2
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: mono2-front
    app.kubernetes.io/part-of: mono2
    app.kubernetes.io/component: front
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
