apiVersion: v1
kind: Service
metadata:
  name: webhook-front
  namespace: webhook
  labels:
    app: webhook-front
    app.kubernetes.io/part-of: webhook
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: webhook-front
    app.kubernetes.io/part-of: webhook
    app.kubernetes.io/component: front
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
