apiVersion: v1
kind: Secret
metadata:
  name: fdfdfdfd-front-secrets
  namespace: fdfdfdfd
type: Opaque
stringData:
  JWT_SECRET: "fdfdfdfd-jwt-secret"
  SPRING_DATA_MONGODB_URI: "mongodb://admin:fdfdfdfd-mongodb-pass@mongodb:27017/appdb?authSource=admin"
  MONGODB_URI: "mongodb://admin:fdfdfdfd-mongodb-pass@mongodb:27017/appdb?authSource=admin"
