apiVersion: v1
kind: Service
metadata:
  name: firas-back
  namespace: firas
  labels:
    app: firas-back
    app.kubernetes.io/part-of: firas
    app.kubernetes.io/component: back
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: firas-back
    app.kubernetes.io/part-of: firas
    app.kubernetes.io/component: back
  ports:
    - name: http
      port: 8080
      targetPort: 8081
      protocol: TCP
