apiVersion: v1
kind: Service
metadata:
  name: bbb-auth-api
  namespace: bbb
  labels:
    app: bbb-auth-api
    app.kubernetes.io/part-of: bbb
    app.kubernetes.io/component: auth-api
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: bbb-auth-api
    app.kubernetes.io/part-of: bbb
    app.kubernetes.io/component: auth-api
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
