apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-test-front
  namespace: build-test
  labels:
    app: build-test-front
    app.kubernetes.io/part-of: build-test
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build-test-front
      app.kubernetes.io/part-of: build-test
      app.kubernetes.io/component: front
  template:
    metadata:
      labels:
        app: build-test-front
        app.kubernetes.io/part-of: build-test
        app.kubernetes.io/component: front
    spec:
      containers:
        - name: front
          image: docker.io/firasmah/build-test-front:run-1775155921749-front
          ports:
            - containerPort: 4200
              protocol: TCP
          envFrom:
            - secretRef:
                name: build-test-front-secrets
                optional: true
            - configMapRef:
                name: build-test-front-config
                optional: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 4200
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 4200
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
