apiVersion: v1
kind: Service
metadata:
  name: monotest2-front
  namespace: monotest2
  labels:
    app: monotest2-front
    app.kubernetes.io/part-of: monotest2
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: monotest2-front
    app.kubernetes.io/part-of: monotest2
    app.kubernetes.io/component: front
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
