apiVersion: v1
kind: Service
metadata:
  name: dfdfdf-front
  namespace: dfdfdf
  labels:
    app: dfdfdf-front
    app.kubernetes.io/part-of: dfdfdf
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: dfdfdf-front
    app.kubernetes.io/part-of: dfdfdf
    app.kubernetes.io/component: front
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
