apiVersion: v1
kind: Service
metadata:
  name: hhh-auth-api
  namespace: hhh
  labels:
    app: hhh-auth-api
    app.kubernetes.io/part-of: hhh
    app.kubernetes.io/component: auth-api
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: hhh-auth-api
    app.kubernetes.io/part-of: hhh
    app.kubernetes.io/component: auth-api
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
