apiVersion: v1
kind: Secret
metadata:
  name: rrreeee-nodejs-shopping-secrets
  namespace: rrreeee
type: Opaque
stringData:
  JWT_SECRET: "rrreeee-jwt-secret"
  SPRING_DATASOURCE_PASSWORD: "rrreeee-mysql-pass"
  SPRING_DATA_MONGODB_URI: "mongodb://admin:rrreeee-mongodb-pass@mongodb:27017/appdb?authSource=admin"
  MONGODB_URI: "mongodb://admin:rrreeee-mongodb-pass@mongodb:27017/appdb?authSource=admin"
  DATABASE_URL: "mysql://admin:rrreeee-mysql-pass@mysql:3306/appdb"
