apiVersion: v1
kind: Secret
metadata:
  name: gggrrr-front-secrets
  namespace: gggrrr
type: Opaque
stringData:
  JWT_SECRET: "gggrrr-jwt-secret"
  SPRING_DATA_MONGODB_URI: "mongodb://admin:gggrrr-mongodb-pass@mongodb:27017/appdb?authSource=admin"
  MONGODB_URI: "mongodb://admin:gggrrr-mongodb-pass@mongodb:27017/appdb?authSource=admin"
