apiVersion: v1
kind: Service
metadata:
  name: gggrrr-front
  namespace: gggrrr
  labels:
    app: gggrrr-front
    app.kubernetes.io/part-of: gggrrr
    app.kubernetes.io/component: front
    managed-by: daas
spec:
  type: ClusterIP
  selector:
    app: gggrrr-front
    app.kubernetes.io/part-of: gggrrr
    app.kubernetes.io/component: front
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
